- name: GPG | Install Python Packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - python
    - python-wheel
    - python-pip

- name: GPG | Install pexpect
  pip:
    name: pexpect

- name: GPG | Create GPG Folder
  file:
    path: "{{ gpg.directory }}"
    state: directory
    mode: 0700

- name: GPG | Create Private Keys
  copy:
    dest: "{{ gpg.directory }}/{{ item.key }}_private_key"
    content: "{{ item.value.content }}"
    mode: 0600
  with_dict: "{{ vault_gpg.private }}"

- name: GPG | Create Public Keys
  copy:
    dest: "{{ gpg.directory }}/{{ item.key }}_public_key"
    content: "{{ item.value.content }}"
    mode: 0600
  with_dict: "{{ gpg.public }}"

- name: GPG | Import Public Keys
  command: "gpg --import {{ gpg.directory }}/{{ item.key }}_public_key"
  with_dict: "{{ gpg.public }}"

- name: GPG | Trust Keys
  expect:
    command: "gpg --edit-key {{ item.value.id }} trust"
    echo: yes
    responses:
      "Your decision?": "5"
      "Do you really want to set this key to ultimate trust?": "y"
      "gpg>": "quit"
  with_dict: "{{ gpg.public }} "
